### ISSUE TITLE
Minimum nuimber of references in a template should be 1?

### ISSUE THREAD

**Issue by arenas-guerrero-julian** [kg-construct/yarrrml-spec#1]
According to R2RML, in a [string template](https://www.w3.org/TR/r2rml/#dfn-string-template)  _"There SHOULD be at least one pair of unescaped curly braces."_, i.e. at least one reference.

However, the YARRRML spec says _"A template contains 0 or more constant strings and 0 or more references to data in a data"_. IMO the second **0** should be a **1**, to be compliant w.r.t. R2RML.

**Comment by andimou** [comment]
I think that the template of YARRRML is not the same as the template of [R2]RML. A YARRRML template covers more than an R2RML template.

**Comment by arenas-guerrero-julian** [comment]
I see,

Thanks!
