### ISSUE TITLE
Target is not in this spec

### ISSUE THREAD

**Issue by dachafra** [kg-construct/yarrrml-spec#3]
The target section is not defined in this spec while in the (rml.io) YARRRML appears: https://rml.io/yarrrml/spec/#targets.

We need to include it here

**Comment by DylanVanAssche** [comment]
It seems the creator of the repo imported the wrong source or the source without Target included.

**Comment by bjdmeest** [comment]
Yeah yeah we all know [that's my bad](0b1d8054542a30c00d160a0f186bca8cd3980d9d) 😅 . Should be fixed now!

**Comment by dachafra** [comment]
thanks!!
